### ISSUE TITLE
Time is only displayed on first destination with space characters in time=* (destination_sign relation)

### ISSUE THREAD

**Issue by dafadllyn** [mueschel/OsmDestinationSigns#12]
If the value of `time=*` in a `type=destination_sign` relations includes space characters, the time is only displayed on the first destination, e.g.:

<img src="https://github.com/mueschel/OsmDestinationSigns/assets/79018751/fce1b144-2c77-4071-a921-66e02bcab88d" width="300" />

`time="0:05; 0:25; 0:40; 0:20; 0:35"`

After having removed the space characters, all durations are displayed:

<img src="https://github.com/mueschel/OsmDestinationSigns/assets/79018751/97df2fd3-5773-48df-8d77-af57022bf3a5" width="300" />

`time="0:05;0:25;0:40;0:20;0:35"`

Example is from here (currently w/o space characters): https://osm.mueschelsoft.de/destinationsign/example/index.htm#node=10087766313&namedroutes=1&fromarrow=0&include_sgn=1&include_way=1&country=

Another example with a space characters after semicolons: https://osm.mueschelsoft.de/destinationsign/example/index.htm#node=10087766313&namedroutes=1&fromarrow=0&include_sgn=1&include_way=1&country=

**Comment by mueschel** [comment]
Thanks for noticing. Indeed one of my parsing strings for the various ways how time is tagged missed the possible spaces.

Here's a relation that still has the spaces:
https://osm.janmichel.eu/destinationsign/example/index.htm#node=8989980795&namedroutes=1&fromarrow=0&include_sgn=1&include_way=1&country=

Should be fixed now!
https://github.com/mueschel/OsmDestinationSigns/commit/e96e3605dd7b22b98288f5313e11d96bed3f1400
