### ISSUE TITLE
`none` is removed from words

### ISSUE THREAD

**Issue by sostock** [mueschel/OsmDestinationSigns#14]
For example, [this way](https://osm.mueschelsoft.de/destinations/example/#wayid=1326236697&direction=0&country=FR) has `Senones` as its destination, but the rendered sign shows `Ses`. Apparently, `none` gets removed even when it is part of another word.
![Screenshot_20241020_134912](https://github.com/user-attachments/assets/98422473-0b8a-4492-9e4b-4891e7b32d3f)

**Comment by mueschel** [comment]
Good catch. Some people add "none" instead of an empty entry, so I have to remove those. My filter wasn't restricted to stand-alone strings, but removed those in the middle of words as well. Fixed in 
https://github.com/mueschel/OsmDestinationToSVG/commit/7fabe994afc12af55a821ff1d200cdf3eb371861
