### ISSUE TITLE
add some new symbols to the code

### ISSUE THREAD

**Issue by ba179** [mueschel/OsmDestinationSigns#3]
adding a few new symbols to the code would be very nice:
e.g.:
div.interchange {  
    background-image:url("https://upload.wikimedia.org/wikipedia/commons/d/d4/RWBA_Autobahnkreuz_oder_-dreieck.svg") ;
    }

div.swimming_hall {  
    background-image:url("https://upload.wikimedia.org/wikipedia/commons/f/fe/Hallenbad-Schild.svg") ;
    }

div.info {  
    background-image:url("https://upload.wikimedia.org/wikipedia/commons/5/56/Zeichen_365-61_-_Informationsstelle%2C_StVO_2013.svg") ;
    }

**Comment by mueschel** [comment]
Danke! Symbole sind ergänzt.
