### ISSUE TITLE
"Link to this node" display "Can not parse input"

### ISSUE THREAD

**Issue by pyrog** [mueschel/OsmDestinationSigns#5]
### How to reproduce it

1. enter a node id i.e 7774190595
2. press "Link to this node"
3. it open a new tab with this malformed URL (a `&` is missing between node id and `namedroutes` parameter)
https://osm.mueschelsoft.de/destinationsign/example/index.htm#node=7774190595namedroutes=0&fromarrow=1&include_sgn=1&include_way=0&country=

<img width="449" alt="Capture d’écran 2021-05-17 à 18 56 37" src="https://user-images.githubusercontent.com/2158081/118527534-b1486100-b741-11eb-8c78-0869d78e530a.png">

**Comment by mueschel** [comment]
Thanks for pointing this out... I really missed the '&' when the box is unchecked.
It's fixed.
