### ISSUE TITLE
destination_sign relation not render correctly?

### ISSUE THREAD

**Issue by Nekzuris** [mueschel/OsmDestinationSigns#8]
Hi,
there are 2 hiking routes that share the same way at first and the signs directions on this tool doesn't look right, maybe I'm missing something or the render should be improved.

![image](https://user-images.githubusercontent.com/48560751/135937797-a3908d52-94a2-4a8e-8c32-c3bb12888b4e.png)
![image](https://user-images.githubusercontent.com/48560751/135937833-ddeecf5c-f89a-4ec3-aebb-4a41596f99be.png)

I think it should look like this:
![image](https://user-images.githubusercontent.com/48560751/135937864-1fe75fb1-e93a-4f4e-bab4-531b9651c894.png)

Links for you to check:
https://www.openstreetmap.org/node/9135444003
https://osm.mueschelsoft.de/destinationsign/example/index.htm#node=9135444003

**Comment by mueschel** [comment]
Hi,
the source of the problem is that there is no relation between the routes the way belongs to and the destination signs. I now added an additional case - if the destination:ref on the sign matches the ref of one of the routes the way belongs to, then only the symbol/name of this route is shown. If there is no match, then still all routes and symbols are shown.

Could you check if this works/fails/makes new problems?

**Comment by Nekzuris** [comment]
Thanks for the quick fix, works perfectly with destination:ref
but I think you messed up the case when there is no match, no symbols are shown

**Comment by Nekzuris** [comment]
Actually after thinking about it, this might be the right thing to do,
there are many sign that indicate a destination without any trail specifically leading to that destination, so it make sense for me to not show any symbol if there is no reference on the destination_sign relation

**Comment by mueschel** [comment]
>  but I think you messed up the case when there is no match, no symbols are shown

Right, should be fixed now. Actually this was more than one case that showed none or the wrong symbol.


> Actually after thinking about it, this might be the right thing to do,
> there are many sign that indicate a destination without any trail specifically leading to that destination, so it make sense for me to not show any symbol if there is no reference on the destination_sign relation

I'm not sure what the best way is. I guess there is no universal solution. In the end, we're trying to show a destination sign that helps the traveler to find the right way. At the intersection, knowing the ref/symbol of the way might help, even if you can't follow this route to your final destination...

**Comment by Nekzuris** [comment]
Perfect, looks good to me now 👍

Also why did you render the text color over some sign ?
![image](https://user-images.githubusercontent.com/48560751/137005596-ba9bf012-b381-4cec-ae4d-e6f9125ed589.png)
from this trails
![image](https://user-images.githubusercontent.com/48560751/137005679-63ea3f50-6a9f-4ddb-82e5-898a2e30432e.png)

**Comment by mueschel** [comment]
That't not the text color, but "green_frame".  "green_frame" is not a valid foreground, so according to the definition of osmc:symbol in the OSM Wiki it has to be text:

> osmc:symbol=waycolor:background[:foreground][[:foreground2]:text:textcolor]

The implementation on waymarked trails uses a slightly less complex syntax:

> osmc:symbol=waycolor:background:foreground[:text:textcolor]

So it's ignored and not printed.
With my implementation, I guess this is what you're after?
osmc:symbol = :green_frame:green:white_stripe::
![image](http://osm.mueschelsoft.de/osmc/generate.pl?osmc=:green_frame:green:white_stripe::&size=150&out=svg)
But it won't show any white in the other implementations available...

**Comment by Nekzuris** [comment]
Oh okay, I just copied the symbol from a nearby trails

this is the symbol, so I'll just remove the frame then
![image](https://user-images.githubusercontent.com/48560751/137016315-ba35ce73-8436-4f6c-9bfd-4a5ca074f798.png)

and how would you tag the destination:ref for this sign? if I separate them with `;` it expect 2 destinations and I shouldn't add "Fontaine de la Cour" twice? Should I just not specify the ref?

**Comment by Nekzuris** [comment]
What about this one?
![image](https://user-images.githubusercontent.com/48560751/137028276-0d1f186e-10c0-4139-b612-45d176f97978.png)

**Comment by mueschel** [comment]
These cases are complicated. I don't think we have a proper tagging scheme yet.
The best possible option (not used yet) might be to have the destination relations as part of the route relations and take the symbols from there - but on the other hand, this doesn't tell us what is actually shown on the signs.

**Comment by Nekzuris** [comment]
Okay, that fine, I just tagged all 4 destinations without any ref for now
